---
{
   "clone": {
      "depth": 50
   },
   "kind": "pipeline",
   "name": "go-1.12-postgres9",
   "services": [
      {
         "image": "postgres:9-alpine",
         "name": "postgres",
         "ports": [
            5432
         ]
      }
   ],
   "steps": [
      {
         "commands": [
            "apk add --no-cache git build-base clang",
            "make lint-proto",
            "git diff --exit-code"
         ],
         "image": "golang:1.12-alpine",
         "name": "lint"
      },
      {
         "commands": [
            "apk add --no-cache build-base git rpm xz",
            "make build"
         ],
         "image": "golang:1.12-alpine",
         "name": "compile"
      },
      {
         "commands": [
            "apk add --no-cache build-base git rpm xz",
            "git config --global user.name \"Test\"",
            "git config --global user.email \"test@coreos.com\"",
            "make unit-test"
         ],
         "image": "golang:1.12-alpine",
         "name": "unit tests"
      },
      {
         "commands": [
            "apk add --no-cache build-base git rpm xz",
            "make db-test"
         ],
         "environment": {
            "CLAIR_TEST_PGSQL": "postgres@postgres:5432"
         },
         "image": "golang:1.12-alpine",
         "name": "db tests"
      }
   ],
   "workspace": {
      "base": "/go",
      "path": "src/github.com/coreos/clair"
   }
}
---
{
   "clone": {
      "depth": 50
   },
   "kind": "pipeline",
   "name": "go-1.12-postgres10",
   "services": [
      {
         "image": "postgres:10-alpine",
         "name": "postgres",
         "ports": [
            5432
         ]
      }
   ],
   "steps": [
      {
         "commands": [
            "apk add --no-cache git build-base clang",
            "make lint-proto",
            "git diff --exit-code"
         ],
         "image": "golang:1.12-alpine",
         "name": "lint"
      },
      {
         "commands": [
            "apk add --no-cache build-base git rpm xz",
            "make build"
         ],
         "image": "golang:1.12-alpine",
         "name": "compile"
      },
      {
         "commands": [
            "apk add --no-cache build-base git rpm xz",
            "git config --global user.name \"Test\"",
            "git config --global user.email \"test@coreos.com\"",
            "make unit-test"
         ],
         "image": "golang:1.12-alpine",
         "name": "unit tests"
      },
      {
         "commands": [
            "apk add --no-cache build-base git rpm xz",
            "make db-test"
         ],
         "environment": {
            "CLAIR_TEST_PGSQL": "postgres@postgres:5432"
         },
         "image": "golang:1.12-alpine",
         "name": "db tests"
      }
   ],
   "workspace": {
      "base": "/go",
      "path": "src/github.com/coreos/clair"
   }
}
---
{
   "clone": {
      "depth": 50
   },
   "kind": "pipeline",
   "name": "go-1.12-postgres11",
   "services": [
      {
         "image": "postgres:11-alpine",
         "name": "postgres",
         "ports": [
            5432
         ]
      }
   ],
   "steps": [
      {
         "commands": [
            "apk add --no-cache git build-base clang",
            "make lint-proto",
            "git diff --exit-code"
         ],
         "image": "golang:1.12-alpine",
         "name": "lint"
      },
      {
         "commands": [
            "apk add --no-cache build-base git rpm xz",
            "make build"
         ],
         "image": "golang:1.12-alpine",
         "name": "compile"
      },
      {
         "commands": [
            "apk add --no-cache build-base git rpm xz",
            "git config --global user.name \"Test\"",
            "git config --global user.email \"test@coreos.com\"",
            "make unit-test"
         ],
         "image": "golang:1.12-alpine",
         "name": "unit tests"
      },
      {
         "commands": [
            "apk add --no-cache build-base git rpm xz",
            "make db-test"
         ],
         "environment": {
            "CLAIR_TEST_PGSQL": "postgres@postgres:5432"
         },
         "image": "golang:1.12-alpine",
         "name": "db tests"
      }
   ],
   "workspace": {
      "base": "/go",
      "path": "src/github.com/coreos/clair"
   }
}
...
